version: '3'
services:
  app:
    image: com.shineSolutions/nab-preparation-transaction-docker:latest
    ports:
    - 8090:8090
    depends_on:
    - db
    environment:
    - spring.profiles.active=prod
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres

