spring:
  profiles:
    active: dev

# Actuator / Management
management:
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8090

#flyway
flyway:
  check-location: true


## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
---
spring:
  profiles: prod
  datasource:
    url: 'jdbc:postgresql://db:5432/postgres'
    username: postgres
    password: password
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        temp:
          use_jdbc_metadata_defaults: false

---
spring:
  profiles: dev

  # Enabling H2 Console
  h2:
    console:
      enabled: true