spring:
  profiles:
    active: dev

# Actuator / Management
management:
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8090


## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
---
spring:
  profiles: prod
  datasource:
    url: 'jdbc:postgresql://db:5432/postgres'
    username: postgres
    password: password
  # The SQL dialect makes Hibernate generate better SQL for the chosen database




---
spring:
  profiles: dev

  # Enabling H2 Console
  h2:
    console:
      enabled: true
  #flyway


