spring:
  profiles:
    active: prod

  #flyway
  flyway:
    check-location: true

# Actuator / Management
management:
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true
---
spring:
  profiles: prod

  # Database
  datasource:
    url: jdbc:postgresql://db:5432/nab-preparation
    username: postgres
    password: password

  # JPA properties
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    url: 'jdbc:postgresql://db:5432/nab-preparation'
    user: 'postgres'
    password: 'password'

server:
  port: 8090

---
spring:
  profiles: dev
  datasource:
    schema: 'classpath*:db/h2/schema.sql'
    data: 'classpath*:db/h2/data.sql'
  # JPA properties
  jpa:
    generate-ddl: true
    show-sql: true
    database: h2
    hibernate:

  # Enabling H2 Console
  h2:
    console:
      enabled: true
server:
  port: 8081
