server.port: 8090

# Enabling H2 Console
spring.h2.console.enabled: true

# Actuator / Management
management.endpoints.web.base-path: "/manage"
management.endpoints.web.exposure.include: "*"
management.endpoint.shutdown.enabled: true